#POST http://54.252.158.19:8081/transaction/request
POST http://localhost:8081/transaction/request
Content-Type: application/json

{
  "requestDh":"20240302150723",
  "cardId": "1010101010101010",
  "amount": 1000,
  "transactionType": "CHG"
}
